begin;
INSERT INTO "master_print_shop" ("active", "name", "email") VALUES (0, 'Bangladesh', 'Jerika.Ayrin@r-pac.com;Mamun.Hossain@r-pac.com;Sarowar.Morshed@r-pac.com;Danisul.Islam@r-pac.com;Aslam.Rana@r-pac.com;Mostafizur.Rahman@r-pac.com');
INSERT INTO "master_print_shop" ("active", "name", "email") VALUES (0, 'All Latin/Central America', 'sebastian.leyton@r-pac.com.sv;damian.saravia@r-pac.com.sv;raquel.polanco@r-pac.com.sv');
INSERT INTO "master_print_shop" ("active", "name", "email") VALUES (0, 'Hong Kong/S China', 'joby.leung@r-pac.com;ken.yung@r-pac.com;viola.chow@r-pac.com;polly.wong@r-pac.com;joyce.li@r-pac.com;nataliesk.cheng@r-pac.com;yan.xie@r-pac.com.cn;cora.lee@r-pac.com;sydney.lam@r-pac.com');
INSERT INTO "master_print_shop" ("active", "name", "email") VALUES (0, 'India', 'Vishal.Gidatkar@r-pac.com;Sarika.Tamhane@r-pac.com;maheshj@r-pacindia.com');
INSERT INTO "master_print_shop" ("active", "name", "email") VALUES (0, 'Korea', 'rpackorea@kornet.net;jaimeh@kornet.net;janisp@kornet.net;ericwoo@kornet.net');
INSERT INTO "master_print_shop" ("active", "name", "email") VALUES (0, 'Pakistan', 'asma@ag-gigi.com.pk;ovais@ag-gigi.com.pk');
INSERT INTO "master_print_shop" ("active", "name", "email") VALUES (0, 'Shanghai/N China', 'leona.wang@r-pac.com.cn;cindy.yang@r-pac.com.cn');
INSERT INTO "master_print_shop" ("active", "name", "email") VALUES (0, 'Vietnam', 'Niranjan.Aluwihare@r-pac.com;Priscilla.Tay@r-pac.com;Helen.Nguyen@r-pac.com;Huong.Ngo@r-pac.com');
commit;